config/routes.rb
DakarParties::Application.routes.draw do
  

  get '/new_sms' => 'djanoa_messages#new_sms', defaults: {format: 'xml'}

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  devise_for :users

  ActiveAdmin.routes(self)

  resources :partenaires

  resources :events

  resources :actualites

  resources :annonces

  resources :category_annonces

  resources :lieus

  resources :category_actus

  resources :category_events

  resources :structures

  resources :users

  resources :galeries

  resources :category_galeries

  root :to => 'home#index'

end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  belongs_to :categoryActu
  attr_accessible :contenu, :titleActu, :categoryActu_id, :picture

  validates :contenu, :presence  => true
  validates :titleActu, :presence  => true

  mount_uploader :picture, PictureUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  # attr_accessible :title, :body
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :categoryAnnonce
  attr_accessible :date_debut, :date_fin, :descAnnonce, :titleAnnonce

  validates :titleAnnonce, :presence  => true
  validates :descAnnonce, :presence  => true
  
end

app/models/category_actu.rb
class CategoryActu < ActiveRecord::Base
  has_many :actualites
  attr_accessible :descCategory, :titleCategory
end

app/models/category_annonce.rb
class CategoryAnnonce < ActiveRecord::Base
  has_many :annonces
  attr_accessible :descCategory, :titleCategory
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  has_many :events
  attr_accessible :descCategory, :titleCategory
end

app/models/category_galerie.rb
class CategoryGalerie < ActiveRecord::Base
  has_many :galeries
  attr_accessible :desc, :titleCategory

  validates :titleCategory, :presence  => true
end

app/models/djanoa_message.rb
class DjanoaMessage < ActiveRecord::Base
  attr_accessible :from, :to, :message

  # Return the words off the sms
  # @return [Array]

  def words
    message.split
  end

  def method_missing(m, *args)
    if m.to_s[/word_(.+)_exists?/]
      return false if $1.to_i.zero?
      return !words[$1.to_i-1].nil?
    elsif m.to_s[/word_(.+)/]
      return nil if $1.to_i.zero?
      return words[$1.to_i-1]
    else
      super
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :categoryEvent
  belongs_to :structure
  belongs_to :lieu
  belongs_to :user
  attr_accessible :annuler, :date_debut, :date_fin, :descEvent, :nombrePersonne, :titleEvent, :picture, :heure_fin, :heure_debut, :user_id
  attr_accessible :categoryEvent_id, :structure_id, :lieu_id
  mount_uploader :picture, PictureUploader
  validates :titleEvent, :presence  => true
  validates :descEvent, :presence  => true

  validates :heure_debut, :presence  => true
  validates :heure_fin, :presence  => true
  validates_presence_of :categoryEvent_id
  validates_presence_of :lieu_id
  validates_presence_of :structure_id

  # def self.search(search)
  # search_condition = "%" + search + "%"
  # find(:all, :conditions => ['titleEvent LIKE ? OR descEvent LIKE ?', search_condition, search_condition])
  # end

end

app/models/galerie.rb
class Galerie < ActiveRecord::Base
  belongs_to :categoryGalerie
  attr_accessible :picture, :title

  validates :title, :presence  => true
end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  has_many :events
  attr_accessible :NomRegion, :descLieu, :nomLieu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

  belongs_to :structure
  attr_accessible :descPartenaire, :email, :nomPartenaire, :telephone
  validates :nomPartenaire, :presence  => true
end

app/models/structure.rb
class Structure < ActiveRecord::Base
  has_many :events
  has_many :partenaires
  attr_accessible :adresse, :descStructure, :email, :nomStructure, :telephone
  validates :nomStructure, :presence  => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :adminActu, :adminEvent, :adresse, :datenaiss, :login, :nom, :prenom, :sexe, :telephone

  validates :email,        :presence => true,
    :format         => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i},
    :uniqueness     => true
  validates :telephone, :presence  => true

  scope :garcons,         where(:sexe => true)
  scope :filles,          where(:sexe => false)
end

app/controllers/category_galeries_controller.rb
class CategoryGaleriesController < InheritedResources::Base
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/category_galeries_helper.rb
module CategoryGaleriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/lieus_helper.rb
module LieusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category_galeries/_form.html.erb
<%= form_for(@category_galery) do |f| %>
  <% if @category_galery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_galery.errors.count, "error") %> prohibited this category_galery from being saved:</h2>

      <ul>
      <% @category_galery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titleCategory %><br />
    <%= f.text_field :titleCategory %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_galeries/edit.html.erb
<h1>Editing category_galery</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_galery %> |
<%= link_to 'Back', category_galeries_path %>

app/views/category_galeries/index.html.erb
<h1>Listing category_galeries</h1>

<table>
  <tr>
    <th>Titlecategory</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @category_galeries.each do |category_galery| %>
  <tr>
    <td><%= category_galery.titleCategory %></td>
    <td><%= category_galery.desc %></td>
    <td><%= link_to 'Show', category_galery %></td>
    <td><%= link_to 'Edit', edit_category_galery_path(category_galery) %></td>
    <td><%= link_to 'Destroy', category_galery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category galerie', new_category_galery_path %>

app/views/category_galeries/new.html.erb
<h1>New category_galery</h1>

<%= render 'form' %>

<%= link_to 'Back', category_galeries_path %>

app/views/category_galeries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titlecategory:</b>
  <%= @category_galery.titleCategory %>
</p>

<p>
  <b>Desc:</b>
  <%= @category_galery.desc %>
</p>


<%= link_to 'Edit', edit_category_galery_path(@category_galery) %> |
<%= link_to 'Back', category_galeries_path %>