config/routes.rb
DakarParties::Application.routes.draw do
  

  get '/new_sms' => 'djanoa_messages#new_sms', defaults: {format: 'xml'}

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  devise_for :users

  ActiveAdmin.routes(self)

  resources :partenaires

  resources :events

  resources :actualites

  resources :annonces

  resources :category_annonces

  resources :lieus

  resources :category_actus

  resources :category_events

  resources :structures

  resources :users

  resources :galeries

  resources :category_galeries

  root :to => 'home#index'

end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  belongs_to :categoryActu
  attr_accessible :contenu, :titleActu, :categoryActu_id, :picture

  validates :contenu, :presence  => true
  validates :titleActu, :presence  => true

  mount_uploader :picture, PictureUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  # attr_accessible :title, :body
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :categoryAnnonce
  attr_accessible :date_debut, :date_fin, :descAnnonce, :titleAnnonce

  validates :titleAnnonce, :presence  => true
  validates :descAnnonce, :presence  => true
  
end

app/models/category_actu.rb
class CategoryActu < ActiveRecord::Base
  has_many :actualites
  attr_accessible :descCategory, :titleCategory
end

app/models/category_annonce.rb
class CategoryAnnonce < ActiveRecord::Base
  has_many :annonces
  attr_accessible :descCategory, :titleCategory
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  has_many :events
  attr_accessible :descCategory, :titleCategory
end

app/models/category_galerie.rb
class CategoryGalerie < ActiveRecord::Base
  has_many :galeries
  attr_accessible :desc, :titleCategory

  validates :titleCategory, :presence  => true
end

app/models/djanoa_message.rb
class DjanoaMessage < ActiveRecord::Base
  attr_accessible :from, :to, :message

  # Return the words off the sms
  # @return [Array]

  def words
    message.split
  end

  def method_missing(m, *args)
    if m.to_s[/word_(.+)_exists?/]
      return false if $1.to_i.zero?
      return !words[$1.to_i-1].nil?
    elsif m.to_s[/word_(.+)/]
      return nil if $1.to_i.zero?
      return words[$1.to_i-1]
    else
      super
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :categoryEvent
  belongs_to :structure
  belongs_to :lieu
  belongs_to :user
  attr_accessible :annuler, :date_debut, :date_fin, :descEvent, :nombrePersonne, :titleEvent, :picture, :heure_fin, :heure_debut, :user_id
  attr_accessible :categoryEvent_id, :structure_id, :lieu_id
  mount_uploader :picture, PictureUploader
  validates :titleEvent, :presence  => true
  validates :descEvent, :presence  => true

  validates :heure_debut, :presence  => true
  validates :heure_fin, :presence  => true
  validates_presence_of :categoryEvent_id
  validates_presence_of :lieu_id
  validates_presence_of :structure_id

  # def self.search(search)
  # search_condition = "%" + search + "%"
  # find(:all, :conditions => ['titleEvent LIKE ? OR descEvent LIKE ?', search_condition, search_condition])
  # end

end

app/models/galerie.rb
class Galerie < ActiveRecord::Base
  belongs_to :categoryGalerie
  attr_accessible :picture, :title

  validates :title, :presence  => true
end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  has_many :events
  attr_accessible :NomRegion, :descLieu, :nomLieu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

  belongs_to :structure
  attr_accessible :descPartenaire, :email, :nomPartenaire, :telephone
  validates :nomPartenaire, :presence  => true
end

app/models/structure.rb
class Structure < ActiveRecord::Base
  has_many :events
  has_many :partenaires
  attr_accessible :adresse, :descStructure, :email, :nomStructure, :telephone
  validates :nomStructure, :presence  => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :adminActu, :adminEvent, :adresse, :datenaiss, :login, :nom, :prenom, :sexe, :telephone

  validates :email,        :presence => true,
    :format         => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i},
    :uniqueness     => true
  validates :telephone, :presence  => true

  scope :garcons,         where(:sexe => true)
  scope :filles,          where(:sexe => false)
end

app/controllers/partenaires_controller.rb
class PartenairesController < InheritedResources::Base
	before_filter :doit_etre_connecte, :admin_partenaire

	def admin_partenaire
		unless user_signed_in? and (current_user.admin? || current_user.adminActu?)
			flash[:notice] = 'Vous ne disposez pas des droits pour cacceder la page.'
      		redirect_to root_path
		end
	end
end

app/helpers/actualites_helper.rb
module ActualitesHelper
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/lieus_helper.rb
module LieusHelper
end

app/helpers/partenaires_helper.rb
module PartenairesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partenaires/_form.html.erb
<%= form_for @partenaire, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nomPartenaire, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nomPartenaire, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :telephone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telephone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descPartenaire, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descPartenaire, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                partenaires_path, :class => 'btn' %>
  </div>
<% end %>

app/views/partenaires/edit.html.erb
<%- model_class = Partenaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/partenaires/index.html.erb
<%- model_class = Partenaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nomPartenaire) %></th>
      <th><%= model_class.human_attribute_name(:telephone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:descPartenaire) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @partenaires.each do |partenaire| %>
      <tr>
        <td><%= link_to partenaire.id, partenaire_path(partenaire) %></td>
        <td><%= partenaire.nomPartenaire %></td>
        <td><%= partenaire.telephone %></td>
        <td><%= partenaire.email %></td>
        <td><%= partenaire.descPartenaire %></td>
        <td><%=l partenaire.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_partenaire_path(partenaire), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      partenaire_path(partenaire),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_partenaire_path,
            :class => 'btn btn-primary' %>

app/views/partenaires/new.html.erb
<%- model_class = Partenaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/partenaires/show.html.erb
<%- model_class = Partenaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nomPartenaire) %>:</strong></dt>
  <dd><%= @partenaire.nomPartenaire %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telephone) %>:</strong></dt>
  <dd><%= @partenaire.telephone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @partenaire.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descPartenaire) %>:</strong></dt>
  <dd><%= @partenaire.descPartenaire %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              partenaires_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_partenaire_path(@partenaire), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              partenaire_path(@partenaire),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>