config/routes.rb
DakarParties::Application.routes.draw do
  

  get '/new_sms' => 'djanoa_messages#new_sms', defaults: {format: 'xml'}

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "home/index"

  devise_for :users

  ActiveAdmin.routes(self)

  resources :partenaires

  resources :events

  resources :actualites

  resources :annonces

  resources :category_annonces

  resources :lieus

  resources :category_actus

  resources :category_events

  resources :structures

  resources :users

  resources :galeries

  resources :category_galeries

  root :to => 'home#index'

end

app/models/actualite.rb
class Actualite < ActiveRecord::Base
  belongs_to :categoryActu
  attr_accessible :contenu, :titleActu, :categoryActu_id, :picture

  validates :contenu, :presence  => true
  validates :titleActu, :presence  => true

  mount_uploader :picture, PictureUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id
  # attr_accessible :title, :body
end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :categoryAnnonce
  attr_accessible :date_debut, :date_fin, :descAnnonce, :titleAnnonce

  validates :titleAnnonce, :presence  => true
  validates :descAnnonce, :presence  => true
  
end

app/models/category_actu.rb
class CategoryActu < ActiveRecord::Base
  has_many :actualites
  attr_accessible :descCategory, :titleCategory
end

app/models/category_annonce.rb
class CategoryAnnonce < ActiveRecord::Base
  has_many :annonces
  attr_accessible :descCategory, :titleCategory
end

app/models/category_event.rb
class CategoryEvent < ActiveRecord::Base
  has_many :events
  attr_accessible :descCategory, :titleCategory
end

app/models/category_galerie.rb
class CategoryGalerie < ActiveRecord::Base
  has_many :galeries
  attr_accessible :desc, :titleCategory

  validates :titleCategory, :presence  => true
end

app/models/djanoa_message.rb
class DjanoaMessage < ActiveRecord::Base
  attr_accessible :from, :to, :message

  # Return the words off the sms
  # @return [Array]

  def words
    message.split
  end

  def method_missing(m, *args)
    if m.to_s[/word_(.+)_exists?/]
      return false if $1.to_i.zero?
      return !words[$1.to_i-1].nil?
    elsif m.to_s[/word_(.+)/]
      return nil if $1.to_i.zero?
      return words[$1.to_i-1]
    else
      super
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :categoryEvent
  belongs_to :structure
  belongs_to :lieu
  belongs_to :user
  attr_accessible :annuler, :date_debut, :date_fin, :descEvent, :nombrePersonne, :titleEvent, :picture, :heure_fin, :heure_debut, :user_id
  attr_accessible :categoryEvent_id, :structure_id, :lieu_id
  mount_uploader :picture, PictureUploader
  validates :titleEvent, :presence  => true
  validates :descEvent, :presence  => true

  validates :heure_debut, :presence  => true
  validates :heure_fin, :presence  => true
  validates_presence_of :categoryEvent_id
  validates_presence_of :lieu_id
  validates_presence_of :structure_id

  # def self.search(search)
  # search_condition = "%" + search + "%"
  # find(:all, :conditions => ['titleEvent LIKE ? OR descEvent LIKE ?', search_condition, search_condition])
  # end

end

app/models/galerie.rb
class Galerie < ActiveRecord::Base
  belongs_to :categoryGalerie
  attr_accessible :picture, :title

  validates :title, :presence  => true
end

app/models/lieu.rb
class Lieu < ActiveRecord::Base
  has_many :events
  attr_accessible :NomRegion, :descLieu, :nomLieu
end

app/models/partenaire.rb
class Partenaire < ActiveRecord::Base

  belongs_to :structure
  attr_accessible :descPartenaire, :email, :nomPartenaire, :telephone
  validates :nomPartenaire, :presence  => true
end

app/models/structure.rb
class Structure < ActiveRecord::Base
  has_many :events
  has_many :partenaires
  attr_accessible :adresse, :descStructure, :email, :nomStructure, :telephone
  validates :nomStructure, :presence  => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :adminActu, :adminEvent, :adresse, :datenaiss, :login, :nom, :prenom, :sexe, :telephone

  validates :email,        :presence => true,
    :format         => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i},
    :uniqueness     => true
  validates :telephone, :presence  => true

  scope :garcons,         where(:sexe => true)
  scope :filles,          where(:sexe => false)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/actualites_helper.rb
module ActualitesHelper
end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end
end

app/helpers/lieus_helper.rb
module LieusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_actu.erb
<% actus=Actualite.all%>
<% if !actus==nil?%>
    <% actus.each do |actu| %>

        <div class="tab-pane fade in active clearfix" >
          <div class="tab-image pull-left">
            <%= image_tag(actu.picture_url, :width => 150, :height => 150) if actu.picture.present? %>
          </div>
          <h4><%=link_to actu.titleActu, actu%></h4>
          <p>
            <%= actu.contenu[0..230].gsub(/\s\w+\s*$/, '...')%>
            <%=link_to raw('<button class="btn btn-round"> Lire la suite </button>') , actu %>
          </p>

        </div>
        <hr/>

<% end %>

<% end %>

<%= link_to raw('<span class="btn btn-primary" style="margin-left: 40%"> Voir Tout <i class="icon-plus icon-white" ></i></span>'), actualites_path%>

app/views/home/_events_jour.erb
<% event_days=Event.all.reverse %>
<% compte=0 %>
<% if !event_days.nil?   %>



                    <% event_days.each do |event_day| %>
                        <% if event_day.date_debut == Date.today   %>

                          <% compte +=1%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>

                        <% modal="myModal"+event_day.id.to_s%>
                        <% hmodal="#"+modal %>


                          <div class="tab-image pull-left"><%= image_tag(event_day.picture_url, :width => 170, :height => 120) if event_day.picture.present? %></div>
                          <h4><%= event_day.date_debut.strftime("%A %d %B") %></h4>
                          <p><%=  event_day.titleEvent %> </p>
                          <a  class="btn btn-round" data-toggle="modal" href="<%= hmodal%>"><span>voir</span></a>
                          <hr/>







                      <div id="<%=modal%>" class="modal hide fade">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3>Details de l'événement</h3>
                      </div>
                      <div class="modal-body">

                                    <table class="table">
                                      <tr>
                                  <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                                  </tr>
                                      <tr>
                                          <td><%= event_day.titleEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><%= event_day.descEvent %></td>
                                      </tr>
                                      <tr>

                                          <td><span style="font-size:1.2em">Date: </span><% event_day.date_debut.strftime("%A %d %B %Y") %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Heure de début: </span><%= event_day.heure_debut.strftime("%H : %M")%></td>
                                      </tr>
                                      <tr>
                                      <td><span style="font-size:1.2em">Lieu: </span><%= lieu.nomLieu%></td>
                                      </tr>


                                      <tr>
                                          <td><span style="font-size:1.2em">nomde de personne: </span><%= event_day.nombrePersonne %> participants</td>
                                      </tr>

                                </table>
                      </div>
                      <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-dismiss="modal" >Close</a>

                      </div>
                    </div>


                      <% end %>
                      <% end %>
                       <% if compte ==0 %>



                        <div class="alert alert-success">
                          <a class="close" data-dismiss="alert"></a>
                          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour aujourd'hui <%= image_tag("smile2.png", :width => 50)%></span>
                        </div>
                       <% end %>

                    <% end %>

app/views/home/_events_mois.erb
<% event_days=Event.all %>
<% compte=0 %>
<% if !event_days==nil?%>
                    <% event_days.each do |event_day| %>
                    <% if (event_day.date_debut >=Date.today) and (event_day.date_debut <= event_day.date_debut.next.at_end_of_month)%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
                          <% compte += 1 %>
                          <% structure=Structure.find_by_id(event_day.structure_id)%>

                        <% modal="myModal"+event_day.id.to_s%>
                        <% hmodal="#"+modal %>


                        <div class="tab-image pull-left"><%= image_tag(event_day.picture_url, :width => 170, :height => 120) if event_day.picture.present? %></div>
                        <h4><%= event_day.date_debut.strftime("%A %d %B") %></h4>
                        <p><%=  event_day.titleEvent %> </p>
                        <a  class="btn btn-round" data-toggle="modal" href="<%= hmodal%>"><span>voir</span></a>
                        <hr/>

                      <% end %>
                      <% end %>
                    <% if compte ==0 %>
        <div class="alert alert-success">
          <a class="close" data-dismiss="alert"></a>
          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour cette semaine <%= image_tag("smile2.png", :width => 50)%></span>
        </div>
                    <% end %>


                    <% end %>

app/views/home/_events_week.erb
<% event_days=Event.all %>
<% compte = 0%>
<% if !event_days==nil?%>
                    <% event_days.each do |event_day| %>
                    <% if (event_day.date_debut >=Date.today) and (event_day.date_debut <= event_day.date_debut.next.at_end_of_week)%>
                          <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
                           <%compte +=1%>
                          <% structure=Structure.find_by_id(event_day.structure_id)%>

                        <% modal="myModal"+event_day.id.to_s%>
                        <% hmodal="#"+modal %>


                        <div class="tab-image pull-left"><%= image_tag(event_day.picture_url, :width => 170, :height => 120) if event_day.picture.present? %></div>
                        <h4><%= event_day.date_debut.strftime("%A %d %B") %></h4>
                        <p><%=  event_day.titleEvent %> </p>
                        <a  class="btn btn-round" data-toggle="modal" href="<%= hmodal%>"><span>voir</span></a>
                        <hr/>

                      <div id=<%=modal%> class="modal hide fade">
                      <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h3>Details de l'événement</h3>
                      </div>
                      <div class="modal-body">

                                    <table class="table">
                                      <tr>
                                  <td><%= image_tag(event_day.picture_url, :width => 240, :height => 120) if event_day.picture.present? %></td>
                                  </tr>
                                      <tr>
                                          <td><%= event_day.titleEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><%= event_day.descEvent %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Date: </span> <%= event_day.date_debut %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">Heure: </span><%= event_day.heure_debut.strftime("%Ih : %M")%></td>
                                      </tr>
                                      <tr>
                                      <td><span style="font-size:1.2em">Lieu: </span><%= lieu.nomLieu%></td>
                                      </tr>

                                      <tr>
                                         <td><span style="font-size:1.2em">Heure: </span><%= event_day.heure_fin.strftime("%Ih : %M") %></td>
                                      </tr>
                                      <tr>
                                          <td><span style="font-size:1.2em">nomde de personne: </span><%= event_day.nombrePersonne %></td>
                                      </tr>

                                </table>
                      </div>
                      <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-dismiss="modal" >Close</a>

                      </div>
                    </div>
                      <% end %>
                      <% end %>
                    <% if compte ==0 %>
                        <div class="alert alert-success">
                          <a class="close" data-dismiss="alert"></a>
                          <span style="font-size: 1.5em; font-family: 'Glyphicons Halflings'" > Hello! Nous avons pas d'événement pour ce mois <%= image_tag("smile2.png", :width => 50)%></span>
                        </div>
                    <% end %>


                    <% end %>

app/views/home/_myContent.erb
<div class="col-sm-7">
  <!-- .row -->
  <div class="row">

    <div class="col-sm-12">

      <!-- tabs -->
      <div class="tabs-framed styled">
        <div class="inner">

          <ul class="tabs clearfix">
            <li class="active"><a href="#events" data-toggle="tab">Aujourd'hui</a></li>
            <li><a href="#reminder" data-toggle="tab">Cette semaine</a></li>
            <li><a href="#starred" data-toggle="tab"><sup class="note">3</sup>Ce mois</a></li>
          </ul>
          <div class="tab-content boxed">
            <div class="tab-pane fade in active clearfix" id="events">
              <%= render :partial => 'home/events_jour' %>
            </div>
            <div class="tab-pane fade clearfix" id="reminder">
              <%= render :partial => 'home/events_week' %>

            </div>
            <div class="tab-pane fade clearfix" id="starred">
              <%= render :partial => 'home/events_mois' %>
            </div>



          </div>
        </div>
      </div>
      <!--/ tabs -->

    </div>

    <div class="col-sm-12">
      <!-- tabs -->
      <div class="tabs-framed styled">
        <div class="inner">
          <div >
            <a href="#" class="btn btn-blue btn-middle"><span>Actualités</span></a>

          </div>
          <div class="tab-content boxed">
            <%= render :partial => 'home/actu' %>


          </div>




        </div>
      </div>
      <!--/ tabs -->

    </div>

  </div>
  <!-- / .row -->
  <br>
  <!-- .row -->
  <div class="row">
    <div class="col-sm-7">

    </div>
    <div class="col-sm-5">
      <!-- row level 2 -->
      <div class="row knobs">
        <div class="col-sm-12 col-xs-6">



        </div>
        <div class="col-sm-12 col-xs-6">

        </div>
      </div>
      <!-- row level 2 -->
    </div>
  </div>
  <!--/ .row -->
  <br><br><br>
  <!-- .row -->
  <div class="row">


  </div>
  <!--/ .row -->

</div>

app/views/home/_nav_actu.html.erb
<div class="col-sm-3">
  <!-- .row -->
  <div class="row">
    <div class="col-sm-12">

    <% event_days=Event.all(:limit => 3)%>
    <% if !event_days.nil?%>
        <% event_days.each do |event_day| %>

            <% lieu=Lieu.find_by_id(event_day.lieu_id)%>
            <% structure=Structure.find_by_id(event_day.structure_id)%>

            <!-- event -->
            <div class="widget-container widget-profile boxed">
              <div class="inner clearfix">
                <div class="avatar"><%= image_tag(event_day.picture_url, :width => 200, :height => 100) if event_day.picture.present? %></div>
                <span><%= event_day.date_debut.strftime("%A %d %B") %></span>
                <span class="subtitle"><%=link_to event_day.titleEvent, root_path%></span>
                <div class="follow">
                  <a href="#" class="btn btn-round"><span>Voir</span></a>
                  <div class="followers pull-right">
                    <strong>à <%= event_day.heure_debut.strftime("%H")%>H : <%= event_day.heure_debut.strftime("%M")%></strong>
                    <span><%= lieu.nomLieu%></span>
                  </div>
                </div>
              </div>
            </div>
            <!--/ event -->

        <% end %>
    <% end %>


    </div>



    <div class="col-sm-12">
      <!-- Profile -->
      <div class="widget-container widget-profile boxed">
        <div class="inner clearfix">
          <a href="#" class="btn btn-blue btn-right"><span>Nous suivre</span></a>
          <hr/>
          <label class="label label-primary"> Facebook</label>
          <label class="label label-info"> Twitter</label>
          <label class="label label-danger"> Google+</label>
        </div>
      </div>
      <!--/ Profile -->
    </div>

    <div class="col-sm-12">
      <!-- search widget -->
      <div class="widget-container widget-search boxed styled">
        <div class="inner">
          <form method="get" id="searchform" action="#">
            <span class="btn btn-middle"><input type="submit" value="Search" /></span>
            <div class="field_text lightPlaceholder"><input name="search" value="" type="text" placeholder="Type word here" /></div>
          </form>
        </div>
      </div>
      <!--/ search widget -->
    </div>





    <!-- /.row -->
  </div>
</div>
<!--/ .row -->

<div class="col-sm-2">

  <!-- tabs -->
  <div class="tabs-framed styled">
    <div class="inner">

      <div class="tab-content boxed">
        <div class="tab-pane fade in active clearfix" >

          <% if user_signed_in? %>
              <% user= current_user%>


              <ul class="nav nav-pills nav-stacked" style="text-align: justify">
                <li class="active">
                  <a href="#" style=""><i class="icon-user icon-white"></i> <%= current_user.login %></a>
                </li>
                <li class=""><%= link_to raw(" <center> <i class='icon-eye-open icon-black' style=''> Mon profil</i> </center>"), user, :class => 'well' %></li>
                <li class=""><%= link_to raw(" <center> <i class='icon-pencil icon-black' style=''> Modifier profil</i> </center>"),edit_user_path(user), :class => 'well' %></li>

                <li ><%= link_to raw(" <center> <i class='icon-off icon-black' style=''> Deconnexion</i></center>"), destroy_user_session_path, :method => :delete, :class => 'btn btn-large', :notice => 'nice' %></li>

              </ul>

              <div class="clearfix"></div>




          <% else %>
              <ul class="nav nav-pills nav-stacked " style="text-align: justify;">
                <li class="active">
                  <a href="#" ><i class="icon-user icon-white"></i> Profil</a>
                </li>
                <li class=""><%= link_to raw(" <i class='icon-hand-right icon-black' style=''> Se connecter</i>"), new_user_session_path, :class => 'well' %>
                </li>
                <li class=""> <%= link_to raw("<center> <i class='icon-plus icon-black' style=''> S'inscrire</i> </center>"), new_user_registration_path, :class => 'well'%></li>
              </ul>

          <% end %>
        </div>


      </div>
      <br/>

      <% if (user_signed_in? and (current_user.admin? || current_user.adminEvent? ) ) %>
      <div class="inner">

        <div class="tab-content boxed">

          <ul class="nav nav-pills nav-stacked">
            <li class="active">
              <a href="#" >Espace Admin</a>
            </li>
            <li ><%= link_to "Espace Evenements", events_path,:class => 'well' %></li>
            <li class="" ><%= link_to "Espace Actualites", actualites_path,:class => 'well' %></li>
            <li class="" ><%= link_to "Espace Annonces", annonces_path,:class => 'well '%></li>
            <li class="" ><%= link_to "Espace Utilisateurs", users_path,:class => 'well' %></li>
          </ul>
          <hr/>
          <ul class="nav nav-pills nav-stacked">
            <li class=""><%= link_to "Creer event", new_event_path, :class => 'well'%></li>
            <li class=""><%= link_to "Créer catégory event", new_category_event_path,:class => 'well'%></li>
            <li class=""><%= link_to "Créer lieu", lieus_path,:class => 'well'%></li>
            <li class=""><%= link_to "Liste des events", events_path,:class => 'well'%></li>
            <li class=""><%= link_to "Catégory des events", category_events_path,:class => 'well'%></li>

          </ul>



        </div>
      </div>

      <% end %>




    </div>
  </div>
  <!--/ tabs -->

</div>

app/views/home/_slider.erb
<!-- .row slider  -->
<div class="row"  style="margin-top: 60px">
  <div class="col-sm-9" >
    <div class="col-sm-12">
      <!-- Image Slider -->
      <div class="widget-container widget-gallery boxed">
        <div class="inner">
          <div id="myCarousel3" class="carousel slide" data-interval="5000">
            <!-- Carousel items -->
            <div class="carousel-inner">
              <div class="active item">
                <a href="images/temp/post-img-1.jpg" data-rel="prettyPhoto" title="Disney’s Brave"><%= image_tag("sl1.jpg")%></a>
                <div class="carousel-desc gradient"><strong>Brave</strong><span>&laquo;Change your fate.&raquo;</span></div>
              </div>
              <div class="item">
                <a href="images/temp/post-img-2.jpg" data-rel="prettyPhoto" title="Ice Age"><%= image_tag("sl2.jpg")%></a>
                <div class="carousel-desc gradient"><strong>Ice Age</strong><span>&laquo;Change your fate.&raquo;</span></div>
              </div>
              <div class="item">
                <a href="images/temp/post-img-3.jpg" data-rel="prettyPhoto" title="Horton"><%= image_tag("sl2.jpg")%></a>
                <div class="carousel-desc gradient"><strong>Horton</strong><span>&laquo;Change your fate.&raquo;</span></div>
              </div>
            </div>
            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel3" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel3" data-slide-to="1"></li>
              <li data-target="#myCarousel3" data-slide-to="2"></li>
            </ol>
            <!-- Carousel nav -->
            <a class="carousel-control left" href="#myCarousel3" data-slide="prev"></a>
            <a class="carousel-control right" href="#myCarousel3" data-slide="next"></a>
          </div>
        </div>
      </div>
      <!--/ Image Slider -->
    </div>
  </div>
  <div class="col-sm-3" >
    <div class="widget-container boxed border-top pink" style="height: 300px" >
      <div class="inner">
        <div class="ribbon">
          <div class="ribbon-stitches-top"></div>
          <span>Big Event</span>
        </div>


        <!-- place your content here -->
        <div class="inner clearfix">

          <div class="avatar">
            <%= image_tag("nix.jpg")%>
          </div>
          <h5> Concert de Nix</h5>
          <span class="subtitle">Au Just 4U</span>
          <br/>
          <div class="follow">
            <a href="#" class="btn btn-round"><span>voir</span></a>

          </div>
        </div>
      </div>
    </div>

  </div>



</div>
<!--/ .row slider -->

app/views/home/index.html.erb
<%= render :partial => 'home/slider' %>

<div class="row">
  <!-- / Content -->
  <%= render :partial => 'home/myContent' %>

  <!-- / .Content -->

  <!-- / nav event -->
  <%= render :partial => 'home/nav_actu' %>
  <!-- / .nav event -->


</div>